# Generated by Django 3.2.7 on 2021-09-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210929_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name', 'date_of_birth']},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Birth',
            new_name='date_of_birth',
        ),
    ]
